const express = require('express');
const router = express.Router();
const { getAvailableSlots, createPaymentIntent, stripeWebhook, getMyBookings, getPropertyBookings, markAttendance, getBookingById } = require('../controllers/bookingController');
const { protect, authorize } = require('../middleware/auth');
const Booking = require('../models/Booking');
const Property = require('../models/Property');

// Public endpoint to check slots
router.route('/slots/:propertyId').get(getAvailableSlots);

router.route('/create-payment-intent').post(protect, createPaymentIntent);

router.route('/my-bookings').get(protect, getMyBookings);

// Daily report routes — must be before /:id to avoid route collision
router.get('/daily-report', protect, authorize('securityOfficer'), async (req, res) => {
  try {
    const Booking = require('../models/Booking');
    const date = req.query.date || new Date().toISOString().split('T')[0];
    const start = new Date(date);
    const end = new Date(date);
    end.setDate(end.getDate() + 1);
    const bookings = await Booking.find({
      date: { $gte: start, $lt: end }
    })
      .populate('customerId', 'name email')
      .populate('propertyId', 'name ownerId')
      .sort('timeSlot.start');
    const confirmed = bookings.filter(b => b.attendanceStatus === 'confirmed').length;
    const noShow = bookings.filter(b => b.attendanceStatus === 'noShow').length;
    const pending = bookings.filter(b => b.attendanceStatus === 'pending').length;
    res.json({ date, total: bookings.length, confirmed, noShow, pending, bookings });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

router.post('/daily-report/send', protect, authorize('securityOfficer'), async (req, res) => {
  try {
    const { date, total, confirmed, noShow, pending, propertyName, ownerId } = req.body;
    const Warning = require('../models/Warning');
    const message = `Daily Report for ${propertyName} — ${date}: ${total} total bookings, ${confirmed} confirmed arrivals, ${noShow} no-shows, ${pending} pending. Generated by security officer.`;
    await Warning.create({
      ownerId,
      complaintId: null,
      message
    });
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

router.route('/property/:propertyId').get(protect, authorize('admin', 'propertyOwner', 'securityOfficer'), getPropertyBookings);

router.post('/create-onsite', protect, authorize('customer'), async (req, res) => {
  try {
    const { propertyId, date, timeSlotStart, timeSlotEnd } = req.body;
    const property = await Property.findById(propertyId);
    if (!property) return res.status(404).json({ message: 'Property not found' });
    const existing = await Booking.findOne({
      propertyId,
      date: new Date(date),
      'timeSlot.start': timeSlotStart,
      status: { $in: ['pending', 'pending_onsite', 'booked'] }
    });
    if (existing) return res.status(400).json({ message: 'This slot is already taken' });
    const booking = await Booking.create({
      propertyId,
      customerId: req.user._id,
      date: new Date(date),
      timeSlot: { start: timeSlotStart, end: timeSlotEnd },
      totalAmount: property.pricePerHour,
      status: 'pending_onsite',
      paymentMethod: 'onsite',
      qrCodeData: JSON.stringify({
        bookingId: 'PLACEHOLDER',
        propertyId,
        customerId: req.user._id,
        timeSlot: { start: timeSlotStart, end: timeSlotEnd },
        paymentMethod: 'onsite'
      })
    });
    booking.qrCodeData = JSON.stringify({
      bookingId: booking._id,
      propertyId,
      customerId: req.user._id,
      timeSlot: { start: timeSlotStart, end: timeSlotEnd },
      paymentMethod: 'onsite'
    });
    await booking.save();
    res.status(201).json(booking);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

router.patch('/:id/mark-paid', protect, authorize('securityOfficer'), async (req, res) => {
  try {
    const booking = await Booking.findById(req.params.id)
      .populate('customerId', 'name')
      .populate('propertyId', 'name');
    if (!booking) return res.status(404).json({ message: 'Booking not found' });
    if (booking.paymentMethod !== 'onsite') {
      return res.status(400).json({ message: 'This booking is not an on-site payment' });
    }
    if (booking.status !== 'pending_onsite') {
      return res.status(400).json({ message: 'Booking is already paid or cancelled' });
    }
    booking.status = 'booked';
    await booking.save();
    res.json(booking);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

router.route('/:id').get(protect, authorize('admin', 'securityOfficer', 'propertyOwner'), getBookingById);
router.route('/:id/attendance').patch(protect, authorize('admin', 'securityOfficer'), markAttendance);

// Raw body parsing for this route is applied in index.js via app.use('/api/bookings/webhook', express.raw(...))
router.post('/webhook', stripeWebhook);

module.exports = router;

